config/routes.rb
Tertulias::Application.routes.draw do

  devise_for :users
  resources :contribution_types
  resources :users do
    member do
      get 'usurp_admin'
      get 'make_admin'
      get 'make_normal'
    end
  end
  resources :events do
    member do
      get 'next'
    end

    resources :comments
    resources :guests do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
    resources :contributions do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
  end

  root :to => 'events#next'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :user, :readonly => true
  belongs_to :event

  validates_presence_of :name
  validates_uniqueness_of :name

  after_initialize :set_default_values

  def belongs_to? someone
    return true if user == nil
    return false if someone == nil
    return user.id == someone.id
  end
  def belongs_to! someone
    raise "Don't hack me bro!" unless belongs_to? someone
  end

  private
    def set_default_values
      return unless new_record?
      self.coming = true if self.coming.nil?
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guests }
    end
  end

  def confirm
    guest = Guest.find(params[:id])
    guest.belongs_to! current_user
    guest.coming = true

    if(guest.save)
    then  redirect_to guest.event, notice: t('tert.guest.Confirmed')
    else  redirect_to  guest.event, notice: t('tert.guest.ConfirmFailed')
    end
  end

  def cancel
    guest = Guest.find(params[:id])
    guest.belongs_to! current_user

    if(guest.destroy)
    then  redirect_to  guest.event, notice: t('tert.guest.Cancelled')
    else  redirect_to  guest.event, notice: t('tert.guest.CancelFailed')
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest = Guest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/new
  # GET /guests/new.json
  def new
    @guest = Guest.new
    @guest.user = current_user
    @event = Event.find(params[:event_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guest }
    end
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(params[:guest])
	  @guest.user = current_user
    @guest.event_id = params[:event_id]
    @event = Event.find(params[:event_id])

    respond_to do |format|
      if @guest.save
        format.html { redirect_to  @guest.event, notice: 'Guest was successfully created.' }
        format.json { render json: @guest, status: :created, location: @guest }
      else
        format.html { render action: "new" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guests/1
  # PUT /guests/1.json
  def update
    @guest = Guest.find(params[:id])

    respond_to do |format|
      if @guest.update_attributes(params[:guest])
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for([@event, @guest]) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/_list.html.erb
<h2><%= pluralize @guests.count, Guest.model_name.human %>:</h2>
<ul>
<% @guests.each do |guest| %>
  <% next if !guest.coming?() && !guest.belongs_to?(current_user) %>
  <li<%= " class='cancelled'" if !guest.coming? %>><%= guest.name %> <small>(<%= guest.user.name %>)</small> <%= 
    if guest.belongs_to? current_user
      if guest.coming?
        then link_to(image_tag('cancel.png'), cancel_event_guest_path(@event, guest))
        else link_to(image_tag('accept.png'), confirm_event_guest_path(@event, guest))
      end
    end
    %></li>
<% end %>
</ul>

<%= link_to t('tert.add_x', :model => Guest.model_name.human), new_event_guest_path(@event), class: 'add' %>

app/views/guests/new.html.erb
<h2><%= t 'tert.new_x.male', :model => Guest.model_name.human %></h2>

<%= render 'form' %>

<%= link_to t('Back'), event_path(@event) %>