config/routes.rb
Tertulias::Application.routes.draw do

  devise_for :users
  resources :contribution_types
  resources :users do
    member do
      get 'usurp_admin'
      get 'make_admin'
      get 'make_normal'
    end
  end
  resources :events do
    member do
      get 'next'
    end

    resources :comments
    resources :guests do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
    resources :contributions do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
  end

  root :to => 'events#next'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user, :readonly => true
	belongs_to :event

	validates_presence_of :title

	def self.latest
		Comment.find(:all, :order => "created_at desc", :limit => 5)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    @comment.user = current_user
    @event = Event.find(params[:event_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @event = Event.find params[:event_id]
    @comment.event = @event

    respond_to do |format|
      if @comment.save
        msg = t('created_x.male', model: Comment.model_name.human)
        format.html { redirect_to @comment.event, notice: msg }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        @comment.event_id = params[:event_id]
        @event = Event.find params[:event_id]
        format.html {
          @comments = Comment.latest
          render action: "new"
        }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@event, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, cols: 60, rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_list.erb
<h2><%= pluralize @comments.count, Comment.model_name.human %>:</h2>

<%= link_to t('tert.add_x', :model => Comment.model_name.human), new_event_comment_path(@event), class: 'add' %>

<ul>
<% @comments.each do |comment| %>
	<li id='comment-<%= comment.id %>'>
		<%= comment.title %> <small>(<%= comment.user.name %> &mdash; <%= l comment.updated_at, format: :long %>)</small><% next unless comment.description? %>:
		<p class="description"><%= comment.description %></p>
	</li>
<% end %>
</ul>

app/views/comments/_mini_form.html.erb
<%= form_for([@event, @new_comment]) do |f| %>
  <div class="field">
    <%= f.label :title %>:
    <%= f.text_field :title, :required => '' %>
  </div>
  <div class="field">
    <%= f.text_area :description, cols: 60, rows: 5, placeholder: Comment.human_attribute_name(:description) %>
  </div>
  <div class="actions">
    <%= f.submit t('tert.Add') %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h2><%= t 'tert.new_x.male', :model => Comment.model_name.human %></h2>

<%= render 'form' %>

<%= link_to t('Back'), event_path(@event) %>