config/routes.rb
Tertulias::Application.routes.draw do

  devise_for :users
  resources :contribution_types
  resources :users do
    member do
      get 'usurp_admin'
      get 'make_admin'
      get 'make_normal'
    end
  end
  resources :events do
    member do
      get 'next'
    end

    resources :comments
    resources :guests do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
    resources :contributions do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
  end

  root :to => 'events#next'

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :user, :readonly => true
  belongs_to :contribution_type
  belongs_to :event

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :contribution_type

  def belongs_to? someone
    return true if user == nil
    return false if someone == nil
    return user.id == someone.id
  end
  def belongs_to! someone
    raise "Don't hack me bro!" unless belongs_to? someone
  end
end

app/models/contribution_type.rb
class ContributionType < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  validates_uniqueness_of :colour, :if => Proc.new{|ct| !ct.colour.blank?}
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contributions }
    end
  end

  def confirm
    contrib = Contribution.find(params[:id])
    contrib.belongs_to! current_user
    contrib.removed = false

    if(contrib.save)
    then  redirect_to contrib.event, notice: t('tert.contribution.Confirmed')
    else  redirect_to  contrib.event, notice: t('tert.contribution.ConfirmFailed')
    end
  end

  def cancel
    contrib = Contribution.find(params[:id])
    contrib.belongs_to! current_user

    if(contrib.destroy)
    then  redirect_to  contrib.event, notice: t('tert.contribution.Cancelled')
    else  redirect_to  contrib.event, notice: t('tert.contribution.CancelFailed')
    end
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
    @contribution = Contribution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contribution }
    end
  end

  # GET /contributions/new
  # GET /contributions/new.json
  def new
    @contribution = Contribution.new
    @contribution.user = current_user
    @event = Event.find params[:event_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contribution }
    end
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(params[:contribution])
    @contribution.user = current_user
    @contribution.event_id = params[:event_id]

    respond_to do |format|
      if @contribution.save
        msg = t('created_x.female', model: Contribution.model_name.human)
        format.html { redirect_to @contribution.event, notice: msg }
        format.json { render json: @contribution, status: :created, location: @contribution }
      else
        @event = Event.find params[:event_id]
        format.html { render action: "new" }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @contribution = Contribution.find params[:id]
    @contribution.belongs_to! current_user
    @event = Event.find params[:event_id]
  end

  def update
    @contribution = Contribution.find(params[:id])
    @contribution.belongs_to! current_user
    @event = Event.find params[:event_id]

    respond_to do |format|
      if @contribution.update_attributes(params[:contribution])
        msg = t :updated_x, model: Contribution.model_name.human
        format.html { redirect_to event_path(@event), notice: msg }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= form_for([@event, @contribution]) do |f| %>
  <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% @contribution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contribution_type %><br />
    <% all_types = ContributionType.all.collect {|t| [ t.name, t.id ] } %>
    <%= f.select :contribution_type_id, all_types %>
    <%= link_to t('manage'), contribution_types_path, class: :edit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contributions/_list.html.erb
<h2><%= pluralize @contributions.count, Contribution.model_name.human %>:</h2>
<table>
	<thead><tr>
		<th><%= Contribution.human_attribute_name :name %></th>
		<th><%= Contribution.human_attribute_name :contribution_type %></th>
		<th><%= Contribution.human_attribute_name :user %></th>
		<th />
	</tr></thead>
	<tbody>
	<% @contributions.each do |contrib| %>
		<% next if contrib.removed?() && !contrib.belongs_to?(current_user) %>
		<tr<%= " class='cancelled'" if contrib.removed? %>>
			<td><%= contrib.name %></td>
			<td style="background-color: <%= contrib.contribution_type.colour %>;"><%= contrib.contribution_type.name %></td>
			<td><%= contrib.user.name %></td>
			<td><% if contrib.belongs_to? current_user %>
					<%= link_to image_tag('pencil.png', alt: t(:edit)), edit_event_contribution_path(@event, contrib) %>
					<%= if contrib.removed?
					    then link_to(image_tag('accept.png'), confirm_event_contribution_path(@event, contrib))
					    else link_to(image_tag('cancel.png'), cancel_event_contribution_path(@event, contrib), :confirm => t('tert.ConfirmDelete_x.female', model: Contribution.model_name.human))
					  end %>
				<% end %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<%= link_to t('tert.add_x', :model => Contribution.model_name.human), new_event_contribution_path(@event), class: 'add' %>

app/views/contributions/_mini_form.html.erb
<%= form_for([@event, @new_contribution]) do |f| %>
  <div class="field">
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contribution_type %>:
    <% all_types = ContributionType.all.collect {|t| [ t.name, t.id ] } %>
    <%= f.select :contribution_type_id, all_types %>
    <% str = t('tert.new_x.male', :model => ContributionType.model_name.human) %>
    <%= link_to str, new_contribution_type_path(:event_id => params[:id]), :class => 'add' %>
  </div>
  <div class="actions">
    <%= f.submit t('tert.add') %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1><%= t 'Edit_x', model: @contribution.class.model_name.human %></h1>

<%= render 'form' %>

<%= link_to t(:Back), event_path(@event) %>

app/views/contributions/new.html.erb
<h2><%= t 'tert.new_x.female', :model => Contribution.model_name.human %></h2>

<%= render 'form' %>

<%= link_to t('Back'), event_path(@event) %>