config/routes.rb
Tertulias::Application.routes.draw do

  devise_for :users
  resources :contribution_types
  resources :users do
    member do
      get 'usurp_admin'
      get 'make_admin'
      get 'make_normal'
    end
  end
  resources :events do
    member do
      get 'next'
    end

    resources :comments
    resources :guests do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
    resources :contributions do
      member do
        get 'confirm'
        get 'cancel'
      end
    end
  end

  root :to => 'events#next'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t 'tert.title' %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul id="menu" class="options">
	<% if user_signed_in? %>
		<li><%= current_user.name %> <%= link_to t(:sign_out), destroy_user_session_path, :method => :delete %>
		<li><%= link_to t(:admin), users_path if current_user.admin? %>
	<% else %>
		<li><%= link_to t(:sign_in), new_user_session_path %>
		<li><%= link_to t(:sign_up), new_user_path %>
	<% end %>
</ul>

<h1><%= t 'tert.title' %></h1>

<% if user_signed_in? %>
	<nav>
	<%= t "tert.Existing_events" %>
		<ul>
			<% id = params[:id].to_i
				Event.all.sort_by(&:when).reverse.each do |e| %>
				<li class='<%= "selected" if e.id == id %><%= " future" if e.future? %>'>
					<%= link_to e.name, e, title: l(e.when, format: :long) %>
			<% end %>
			<li><%= link_to t('tert.add_x', :model => Event.model_name.human), new_event_path, class: :add %>
		</ul>
	</nav>
<% end %>

<div id="messages">
	<%= "<p class='notice'>#{notice}</p>".html_safe if notice %>
	<%= "<p class='alert'>#{alert}</p>".html_safe if alert %>
</div>

<%= yield %>

</body>
</html>